FROM golang:1.22 AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o freight-calculator cmd/main.go

FROM scratch 

COPY --from=builder /app/.env .
COPY --from=builder /app/freight-calculator .

CMD ["./freight-calculator"]